# Generated by Django 3.2.23 on 2024-01-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nemone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('dec', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='resume/media')),
            ],
        ),
    ]
