# Generated by Django 3.2.23 on 2024-01-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_karmand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='karmand',
            old_name='jab',
            new_name='job',
        ),
        migrations.RemoveField(
            model_name='karmand',
            name='dec',
        ),
    ]
