# Generated by Django 3.2.23 on 2024-01-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20240105_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karmand',
            name='image',
            field=models.ImageField(null=True, upload_to='resume/media'),
        ),
        migrations.AlterField(
            model_name='karmand',
            name='job',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='karmand',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
